services:
  api:
    build: .
    container_name: api
    ports:
      - "8081:8080"
    networks:
      - minitwitter
    depends_on:
      - db
      - cache
    environment:
      - ConnectionStrings:DefaultConnection=Server=db;Port=5432;Database=MiniTwitter;User Id=postgres;Password=1498AA!

  db:
    image: postgres:latest
    container_name: postgres
    networks:
      - minitwitter
    hostname: db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1498AA!
    ports:
      - "5432:5432"

  cache:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - minitwitter
    ports:
      - '6379:6379'

networks:
  minitwitter:

volumes:
  postgresdata: